setup:
  ansible: .prbuilds/setup.playbook.yml
teardown:
  ansible: .prbuilds/cleanup.playbook.yml
checks:
  screenshots:
      url: http://localhost:9000/books/2014/may/21/guardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism
  exceptions:
      url: http://localhost:9000/books/2014/may/21/guardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism
  a11yvalidation:
        dummy: dummy
