name: Snyk PR
on:
    pull_request:
        paths:
            - 'project/Dependencies.scala'
            - 'project/ProjectSettings.scala'
            - 'project/plugins.sbt'
            - 'package.json'
jobs:
    security:
        uses: guardian/.github/.github/workflows/sbt-node-snyk-pr.yml@main
        with:
            ORG: guardian-frontend
            SEVERITY_THRESHOLD: critical
        secrets:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
