# This action runs every day at 6 AM and on every push
# If the branch it's running on is main then it will run snyk monitor (reports vulnerabilities to snyk.io)
# Otherwise it will run snyk test
name: Snyk - Scala

on:
    schedule:
        - cron: '0 6 * * *'
    push:
    workflow_dispatch:

jobs:
    security:
        runs-on: ubuntu-latest
        env:
            SNYK_COMMAND: test
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Set command to monitor
              if: github.ref == 'refs/heads/main'
              run: echo "SNYK_COMMAND=monitor" >> $GITHUB_ENV

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/scala@0.3.0
              continue-on-error: true # To make sure that SARIF upload gets called
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  args: --org=the-guardian --project-name=${{ github.repository }} --file=build.sbt --sarif-file-output=snyk-scala.sarif

                  command: ${{ env.SNYK_COMMAND }}
            - name: Upload result to GitHub Code Scanning
              if: github.ref != 'refs/heads/main'
              uses: github/codeql-action/upload-sarif@v1
              with:
                  sarif_file: snyk-scala.sarif
